import HTMLHead from "./partials/Head"
import Header from "./Header"

export default function Layout({children}) {
  const title = 'Facade Thoughts'
  const meta = [{name: "description", content: "Generated by create next app"}]
  return (
    <>
      <Header/>
      <HTMLHead title={title} meta={meta}/>
      {children}
    </>
  )
}
